// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuQ8uLepxS1-odfBVPuuFpgOfYIG0u80w',
    appId: '1:357343015182:web:179a4c0d79201f485d275f',
    messagingSenderId: '357343015182',
    projectId: 'sparksteel-87c43',
    authDomain: 'sparksteel-87c43.firebaseapp.com',
    storageBucket: 'sparksteel-87c43.firebasestorage.app',
    measurementId: 'G-KS2HZLF6J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahI5SiFyPw-BzzHyzcgHO7D4PMBEVR9s',
    appId: '1:357343015182:android:d92f1af9b9600ea95d275f',
    messagingSenderId: '357343015182',
    projectId: 'sparksteel-87c43',
    storageBucket: 'sparksteel-87c43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ihUQ8m_RAryPx9d8QfaNTcWntJIlNWA',
    appId: '1:357343015182:ios:4a370870ffc97ef45d275f',
    messagingSenderId: '357343015182',
    projectId: 'sparksteel-87c43',
    storageBucket: 'sparksteel-87c43.firebasestorage.app',
    iosBundleId: 'com.example.sparlsteel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ihUQ8m_RAryPx9d8QfaNTcWntJIlNWA',
    appId: '1:357343015182:ios:4a370870ffc97ef45d275f',
    messagingSenderId: '357343015182',
    projectId: 'sparksteel-87c43',
    storageBucket: 'sparksteel-87c43.firebasestorage.app',
    iosBundleId: 'com.example.sparlsteel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuQ8uLepxS1-odfBVPuuFpgOfYIG0u80w',
    appId: '1:357343015182:web:c0491f04b67eaae45d275f',
    messagingSenderId: '357343015182',
    projectId: 'sparksteel-87c43',
    authDomain: 'sparksteel-87c43.firebaseapp.com',
    storageBucket: 'sparksteel-87c43.firebasestorage.app',
    measurementId: 'G-DGFM6QD0Y4',
  );
}
